// Code generated by re2c 3.1, DO NOT EDIT.
package main

func re2Email3Rule(bytes []byte) int {
	var count int
	var cur, mar int
	bytes = append(bytes, byte(0)) // add terminating null
	lim := len(bytes) - 1          // lim points at the terminating null

	for {
		{
			var yych byte
			yyaccept := 0
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy3
			case ';':
				goto yy4
			default:
				if lim <= cur {
					goto yy123
				}
				goto yy1
			}
		yy1:
			cur += 1
		yy2:
			{
				continue
			}
		yy3:
			yyaccept = 0
			cur += 1
			mar = cur
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy5
			case '@':
				goto yy7
			default:
				goto yy2
			}
		yy4:
			yyaccept = 0
			cur += 1
			mar = cur
			yych = bytes[cur]
			switch yych {
			case 'b':
				goto yy8
			default:
				goto yy2
			}
		yy5:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy9
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy6:
			cur = mar
			if yyaccept == 0 {
				goto yy2
			} else {
				goto yy122
			}
		yy7:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case 0x00:
				goto yy6
			case '.':
				goto yy10
			default:
				goto yy11
			}
		yy8:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case 'a':
				goto yy12
			default:
				goto yy6
			}
		yy9:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy13
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy10:
			cur += 1
			yych = bytes[cur]
		yy11:
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy10
			case '.':
				goto yy14
			default:
				goto yy6
			}
		yy12:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case 's':
				goto yy15
			default:
				goto yy6
			}
		yy13:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy16
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy14:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy17
			default:
				goto yy6
			}
		yy15:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case 'e':
				goto yy19
			default:
				goto yy6
			}
		yy16:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy20
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy17:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy17
			default:
				goto yy18
			}
		yy18:
			{
				count += 1
				continue
			}
		yy19:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '6':
				goto yy21
			default:
				goto yy6
			}
		yy20:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy22
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy21:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '4':
				goto yy23
			default:
				goto yy6
			}
		yy22:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy24
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy23:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case ',':
				goto yy25
			default:
				goto yy6
			}
		yy24:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy26
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy25:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy27
			default:
				goto yy6
			}
		yy26:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy29
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy27:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy27
			case '=':
				goto yy30
			default:
				goto yy28
			}
		yy28:
			{
				continue
			}
		yy29:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy31
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy30:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '=':
				goto yy30
			default:
				goto yy28
			}
		yy31:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy32
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy32:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy33
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy33:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy34
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy34:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy35
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy35:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy36
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy36:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy37
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy37:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy38
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy38:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy39
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy39:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy40
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy40:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy41
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy41:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy42
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy42:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy43
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy43:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy44
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy44:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy45
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy45:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy46
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy46:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy47
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy47:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy48
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy48:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy49
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy49:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy50
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy50:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy51
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy51:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy52
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy52:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy53
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy53:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy54
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy54:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy55
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy55:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy56
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy56:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy57
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy57:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy58
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy58:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy59
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy59:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy60
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy60:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy61
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy61:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy62
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy62:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy63
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy63:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy64
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy64:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy65
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy65:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy66
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy66:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy67
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy67:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy68
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy68:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy69
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy69:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy70
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy70:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy71
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy71:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy72
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy72:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy73
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy73:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy74
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy74:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy75
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy75:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy76
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy76:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy77
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy77:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy78
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy78:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy79
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy79:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy80
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy80:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy81
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy81:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy82
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy82:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy83
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy83:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy84
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy84:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy85
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy85:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy86
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy86:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy87
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy87:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy88
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy88:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy89
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy89:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy90
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy90:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy91
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy91:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy92
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy92:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy93
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy93:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy94
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy94:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy95
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy95:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy96
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy96:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy97
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy97:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy98
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy98:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy99
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy99:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy100
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy100:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy101
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy101:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy102
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy102:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy103
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy103:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy104
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy104:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy105
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy105:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy106
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy106:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy107
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy107:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy108
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy108:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy109
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy109:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy110
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy110:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy111
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy111:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy112
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy112:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy113
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy113:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy114
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy114:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy115
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy115:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy116
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy116:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy117
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy117:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy118
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy118:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy119
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy119:
			cur += 1
			yych = bytes[cur]
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy121
			default:
				goto yy6
			}
		yy120:
			yyaccept = 1
			cur += 1
			mar = cur
			yych = bytes[cur]
		yy121:
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy120
			case '@':
				goto yy7
			default:
				goto yy122
			}
		yy122:
			{
				continue
			}
		yy123:
			{
				return count
			}
		}

	}
}
