// Code generated by re2c 3.1, DO NOT EDIT.
package main

func re2EmailCustomCheck(bytes []byte) int {
	var count int
	var cur, mar int
	lim := len(bytes)

	// Peek function
	peek := func(bytes []byte, cur int, lim int) byte {
		if cur < lim {
			return bytes[cur]
		}
		return 0 // fake null
	}

	for {
		{
			var yych byte
			yych = peek(bytes, cur, lim)
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy3
			default:
				if lim <= cur {
					goto yy13
				}
				goto yy1
			}
		yy1:
			cur += 1
		yy2:
			{
				continue
			}
		yy3:
			cur += 1
			mar = cur
			yych = peek(bytes, cur, lim)
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy5
			default:
				goto yy2
			}
		yy4:
			cur += 1
			yych = peek(bytes, cur, lim)
		yy5:
			switch yych {
			case '+':
				fallthrough
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy4
			case '@':
				goto yy7
			default:
				goto yy6
			}
		yy6:
			cur = mar
			goto yy2
		yy7:
			cur += 1
			yych = peek(bytes, cur, lim)
			switch yych {
			case 0x00:
				goto yy6
			case '.':
				goto yy8
			default:
				goto yy9
			}
		yy8:
			cur += 1
			yych = peek(bytes, cur, lim)
		yy9:
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy8
			case '.':
				goto yy10
			default:
				goto yy6
			}
		yy10:
			cur += 1
			yych = peek(bytes, cur, lim)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy11
			default:
				goto yy6
			}
		yy11:
			cur += 1
			yych = peek(bytes, cur, lim)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy11
			default:
				goto yy12
			}
		yy12:
			{
				count += 1
				continue
			}
		yy13:
			{
				return count
			}
		}

	}
}
