// Code generated by re2c 3.1, DO NOT EDIT.
package main

import "bytes"

func re2Email3RuleBV(input []byte) int {
	var YYMAXFILL int = 101

	var count int
	var cur, mar int
	input = append(input, bytes.Repeat([]byte{0}, YYMAXFILL)...)
	lim := len(input)

	for {
		{
			var yych byte
			yyaccept := 0
			yybm := []byte{
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 160, 0, 152, 144, 32,
				184, 184, 184, 184, 184, 184, 184, 184,
				184, 184, 0, 0, 0, 64, 0, 0,
				0, 184, 184, 184, 184, 184, 184, 184,
				184, 184, 184, 184, 184, 184, 184, 184,
				184, 184, 184, 184, 184, 184, 184, 184,
				184, 184, 184, 0, 0, 0, 0, 152,
				0, 184, 184, 184, 184, 184, 184, 184,
				184, 184, 184, 184, 184, 184, 184, 184,
				184, 184, 184, 184, 184, 184, 184, 184,
				184, 184, 184, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
				0, 0, 0, 0, 0, 0, 0, 0,
			}
			if lim-cur < 101 {
				panic(`fill unexpected`)
			}
			yych = input[cur]
			if yych <= ':' {
				if yych <= ',' {
					if yych <= 0x00 {
						goto yy1
					}
					if yych == '+' {
						goto yy4
					}
					goto yy2
				} else {
					if yych == '/' {
						goto yy2
					}
					if yych <= '9' {
						goto yy4
					}
					goto yy2
				}
			} else {
				if yych <= '^' {
					if yych <= ';' {
						goto yy5
					}
					if yych <= '@' {
						goto yy2
					}
					if yych <= 'Z' {
						goto yy4
					}
					goto yy2
				} else {
					if yych == '`' {
						goto yy2
					}
					if yych <= 'z' {
						goto yy4
					}
					goto yy2
				}
			}
		yy1:
			cur += 1
			{
				return count
			}
		yy2:
			cur += 1
		yy3:
			{
				continue
			}
		yy4:
			yyaccept = 0
			cur += 1
			mar = cur
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy6
					}
					goto yy3
				} else {
					if yych == '/' {
						goto yy3
					}
					if yych <= '9' {
						goto yy6
					}
					goto yy3
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy6
					}
					goto yy3
				} else {
					if yych == '`' {
						goto yy3
					}
					if yych <= 'z' {
						goto yy6
					}
					goto yy3
				}
			}
		yy5:
			yyaccept = 0
			cur += 1
			mar = cur
			yych = input[cur]
			if yych == 'b' {
				goto yy9
			}
			goto yy3
		yy6:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy10
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych <= '9' {
						goto yy10
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy10
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy10
					}
				}
			}
		yy7:
			cur = mar
			if yyaccept == 0 {
				goto yy3
			} else {
				goto yy34
			}
		yy8:
			cur += 1
			yych = input[cur]
			if yych == '.' {
				goto yy11
			}
			goto yy12
		yy9:
			cur += 1
			yych = input[cur]
			if yych == 'a' {
				goto yy13
			}
			goto yy7
		yy10:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy14
					}
					goto yy7
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych <= '9' {
						goto yy14
					}
					goto yy7
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy14
					}
					goto yy7
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy14
					}
					goto yy7
				}
			}
		yy11:
			cur += 1
			if lim-cur < 2 {
				panic(`fill unexpected`)
			}
			yych = input[cur]
		yy12:
			if yybm[0+yych]&8 != 0 {
				goto yy11
			}
			if yych <= ',' {
				goto yy7
			}
			if yych <= '.' {
				goto yy15
			}
			goto yy7
		yy13:
			cur += 1
			yych = input[cur]
			if yych == 's' {
				goto yy16
			}
			goto yy7
		yy14:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy17
					}
					goto yy7
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych <= '9' {
						goto yy17
					}
					goto yy7
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy17
					}
					goto yy7
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy17
					}
					goto yy7
				}
			}
		yy15:
			cur += 1
			yych = input[cur]
			if yybm[0+yych]&16 != 0 {
				goto yy18
			}
			goto yy7
		yy16:
			cur += 1
			yych = input[cur]
			if yych == 'e' {
				goto yy19
			}
			goto yy7
		yy17:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy20
					}
					goto yy7
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych <= '9' {
						goto yy20
					}
					goto yy7
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy20
					}
					goto yy7
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy20
					}
					goto yy7
				}
			}
		yy18:
			cur += 1
			if lim-cur < 1 {
				panic(`fill unexpected`)
			}
			yych = input[cur]
			if yybm[0+yych]&16 != 0 {
				goto yy18
			}
			{
				count += 1
				continue
			}
		yy19:
			cur += 1
			yych = input[cur]
			if yych == '6' {
				goto yy21
			}
			goto yy7
		yy20:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy22
					}
					goto yy7
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych <= '9' {
						goto yy22
					}
					goto yy7
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy22
					}
					goto yy7
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy22
					}
					goto yy7
				}
			}
		yy21:
			cur += 1
			yych = input[cur]
			if yych == '4' {
				goto yy23
			}
			goto yy7
		yy22:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy24
					}
					goto yy7
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych <= '9' {
						goto yy24
					}
					goto yy7
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy24
					}
					goto yy7
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy24
					}
					goto yy7
				}
			}
		yy23:
			cur += 1
			yych = input[cur]
			if yych == ',' {
				goto yy25
			}
			goto yy7
		yy24:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy26
					}
					goto yy7
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych <= '9' {
						goto yy26
					}
					goto yy7
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy26
					}
					goto yy7
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy26
					}
					goto yy7
				}
			}
		yy25:
			cur += 1
			yych = input[cur]
			if yybm[0+yych]&32 != 0 {
				goto yy27
			}
			goto yy7
		yy26:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy29
					}
					goto yy7
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych <= '9' {
						goto yy29
					}
					goto yy7
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy29
					}
					goto yy7
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy29
					}
					goto yy7
				}
			}
		yy27:
			cur += 1
			if lim-cur < 1 {
				panic(`fill unexpected`)
			}
			yych = input[cur]
			if yybm[0+yych]&32 != 0 {
				goto yy27
			}
			if yych == '=' {
				goto yy30
			}
		yy28:
			{
				continue
			}
		yy29:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych == '+' {
						goto yy31
					}
					goto yy7
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych <= '9' {
						goto yy31
					}
					goto yy7
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych <= 'Z' {
						goto yy31
					}
					goto yy7
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy31
					}
					goto yy7
				}
			}
		yy30:
			cur += 1
			if lim-cur < 1 {
				panic(`fill unexpected`)
			}
			yych = input[cur]
			if yybm[0+yych]&64 != 0 {
				goto yy30
			}
			goto yy28
		yy31:
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '?' {
				if yych <= ',' {
					if yych != '+' {
						goto yy7
					}
				} else {
					if yych == '/' {
						goto yy7
					}
					if yych >= ':' {
						goto yy7
					}
				}
			} else {
				if yych <= '^' {
					if yych <= '@' {
						goto yy8
					}
					if yych >= '[' {
						goto yy7
					}
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych >= '{' {
						goto yy7
					}
				}
			}
			cur += 1
			yych = input[cur]
			if yych <= '9' {
				if yych <= ',' {
					if yych == '+' {
						goto yy33
					}
					goto yy7
				} else {
					if yych == '/' {
						goto yy7
					}
					goto yy33
				}
			} else {
				if yych <= '^' {
					if yych <= '?' {
						goto yy7
					}
					if yych <= 'Z' {
						goto yy33
					}
					goto yy7
				} else {
					if yych == '`' {
						goto yy7
					}
					if yych <= 'z' {
						goto yy33
					}
					goto yy7
				}
			}
		yy32:
			yyaccept = 1
			cur += 1
			mar = cur
			if lim-cur < 2 {
				panic(`fill unexpected`)
			}
			yych = input[cur]
		yy33:
			if yybm[0+yych]&128 != 0 {
				goto yy32
			}
			if yych == '@' {
				goto yy8
			}
		yy34:
			{
				continue
			}
		}

	}
}
